events {
    worker_connections 1024;
}

http {
    client_max_body_size 50m;

    upstream auth_service {
        server auth:8001;
    }

    upstream processor_service {
        server processor:8002;
    }

    upstream marketplace_service {
        server marketplace:8003;
    }

    server {
        listen 80;

        location /api/auth/ {
            proxy_pass http://auth_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/processor/ {
            proxy_pass http://processor_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api/marketplace/ {
            proxy_pass http://marketplace_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
}
